#pragma once

#include <tchar.h>

#define FX_NEGATIVE _T("Negative")
#define FX_COLOR_KEY _T("Color Key")
#define FX_DIP_TO_COLOR _T("Dip To Color")
#define FX_SONY_BLUR _T("Sony Blur")
#define FX_AMOEBA_WIPE _T("Amoeba Wipe")
#define FX_PUSH _T("Push")
#define FX_BARM_WIPE _T("Barm Wipe")
#define FX_FAN_WIPE _T("Fan Wipe")
#define FX_MULTI_AXIS_ROTARY_WIPE _T("Multi-Axis Rotary Wipe")
#define FX_MATRIX_WIPE _T("Matrix Wipe")
#define FX_REVOLVING_WIPE _T("Revolving Wipe")
#define FX_RIPPLE_WIPE	_T("Ripple Wipe")
#define FX_SONY_SLIDE _T("Sony Slide")
#define FX_SONY_MASK _T("Sony Mask")
#define FX_CHROMA_KEY _T("Chroma Key")
#define FX_PAGE_ROTATION _T("Page Rotation")
#define FX_PAGE_ROLL _T("Page Roll")
#define FX_DUO_PAGE_ROLL _T("Duo Page Roll")
#define FX_QUAD_PAGE_ROLL _T("Quad Page Roll")
#define FX_SONY_DME_3D_TRANSFORM _T("Soney DME 3D Transform")
#define FX_CUBE_TRANS _T("Cube Trans")
#define FX_SONY_BARN_SLIDE _T("Sony Barn Slide")
#define FX_BROKEN_GLASS _T("Broken Glass")
#define FX_DISSOLVE _T("Dissolve")
#define FX_FADE_FROM_TO _T("Sony Fade From To")
#define FX_SONY_PINP _T("Sony PinP")
#define FX_SONY_3D_BROKEN_GLASS _T("Sony 3D Broken Glass")

