//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TestClient.rc
//
#define IDOK2                           2
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_DIALOGBAR                   103
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_TestClientTYPE              130
#define IDS_EDIT_MENU                   306
#define IDD_DIALOGBAR_IMAGE             311
#define IDD_DIALOG2                     312
#define IDD_BLUR                        312
#define IDD_DIALOG3                     313
#define IDD_COLOR_KEY                   313
#define IDD_AMOEBA_WIPE                 314
#define IDD_PARAM_BARM_WIPE             315
#define IDD_PARAM_BASIC_WIPE            315
#define IDD_PARAM_PUSH                  317
#define IDD_PARAM_CHROMA_KEY            318
#define IDD_DIALOG_SONY_SLIDE           319
#define IDD_PAGE_ROLL                   320
#define IDD_QUAD_PAGE_ROLL              321
#define IDD_CUBE                        323
#define IDD_PARAM_SONY_DME3D            324
#define IDD_PARAM_PINP                  325
#define IDD_SONY_BARN_SLIDE             326
#define IDD_BROKEN_GLASS                327
#define IDD_DISSOLVE                    328
#define IDD_FADE_FROM_TO                329
#define IDD_PAGE_ROTATION               330
#define IDD_QUAD_PAGE_ROLL1             331
#define IDD_DUO_PAGE_ROLL               331
#define IDD_SONY3D_BROKEN_GLASS         332
#define IDC_EFFECTS                     1000
#define IDC_PROGRESS                    1001
#define IDC_BUTTON1                     1002
#define IDC_PARAMETERS                  1002
#define IDC_SELECT_IMAGE1               1002
#define IDC_BUTTON_GET_KEY_COLOR_FROM_SCREEN 1002
#define IDC_IMAGE1                      1003
#define IDC_IMAGE2                      1004
#define IDC_SELECT_IMAGE2               1005
#define IDC_WIDTH                       1006
#define IDC_EDIT3                       1007
#define IDC_HEIGHT                      1007
#define IDC_EDIT_BLUR_X                 1007
#define IDC_EDIT_BLUR_Y                 1008
#define IDC_SLIDER_R                    1010
#define IDC_SLIDER_PROGRESS             1011
#define IDC_SLIDER_PHASE                1012
#define IDC_SLIDER_DIVIDE_WIDTH         1012
#define IDC_SLIDER_divideX              1012
#define IDC_SLIDER_BUMP_DENSITY         1013
#define IDC_SLIDER_DIVIDE_TYPE          1013
#define IDC_SLIDER_DIVIDE_WIDTH2        1013
#define IDC_SLIDER_REVERSE              1013
#define IDC_SLIDER_divideY              1013
#define IDC_SLIDER_SLANT                1014
#define IDC_SLIDER_OFFSET1              1014
#define IDC_SLIDER_DIVIDE_WIDTH3        1014
#define IDC_SLIDER_FIRSTSOFTNESS        1014
#define IDC_SLIDER_fallingDirection     1014
#define IDC_SLIDER_HEIGHT               1015
#define IDC_SLIDER_CENTER_X             1015
#define IDC_SLIDER_DIVIDE_WIDTH4        1015
#define IDC_SLIDER_FIRSTCOLOR           1015
#define IDC_SLIDER_FIRSTCOLOR_R         1015
#define IDC_SLIDER_rotateType           1015
#define IDC_SLIDER_SOFT_EDGE            1016
#define IDC_SLIDER_CENTER_Y             1016
#define IDC_SLIDER_DIVIDE_WIDTH5        1016
#define IDC_SLIDER_SECOND_SOFTNESS      1016
#define IDC_SLIDER_SECONDSOFTNESS       1016
#define IDC_SLIDER_RANDOM_SEED          1017
#define IDC_SLIDER_INVERT               1017
#define IDC_SLIDER_DIVIDE_WIDTH6        1017
#define IDC_SLIDER_SECONDCOLOR          1017
#define IDC_SLIDER_SECONDCOLOR_R        1017
#define IDC_SLIDER_BRIGHTNESS           1018
#define IDC_SLIDER_TRANSPARENCY         1018
#define IDC_SLIDER_DWTYPE               1018
#define IDC_SLIDER_FIRSTCOLOR_G         1018
#define IDC_SLIDER_LIGHT_ANGLE          1019
#define IDC_SLIDER_MULTIPLE_TYPE        1019
#define IDC_COMBO_DWTYPE                1019
#define IDC_SLIDER_HIGH_COLOR_R         1020
#define IDC_SLIDER_MULTIPLE_NUMBER_X    1020
#define IDC_CHECK_REVERSE               1020
#define IDC_SLIDER_HIGH_COLOR_G         1021
#define IDC_SLIDER_MULTIPLE_NUMBER_Y    1021
#define IDC_SLIDER_FIRSTCOLOR_B         1021
#define IDC_CHECK_COLOR_KEY             1021
#define IDC_SLIDER_G                    1022
#define IDC_SLIDER_HIGH_COLOR_B         1022
#define IDC_SLIDER_PATTERN              1022
#define IDC_SLIDER_SECONDCOLOR_G        1022
#define IDC_SLIDER_CK_CLIP              1022
#define IDC_SLIDER_B                    1023
#define IDC_SLIDER_HIGH_COLOR_A         1023
#define IDC_SLIDER_FLIP                 1023
#define IDC_SLIDER_SECONDCOLOR_B        1023
#define IDC_SLIDER_CK_GAIN              1023
#define IDC_SLIDER_ANGLE                1023
#define IDC_SLIDER_A                    1024
#define IDC_SLIDER_LOW_COLOR_R          1024
#define IDC_SLIDER_OVERLAP              1024
#define IDC_SLIDER_SECONDCOLOR4         1024
#define IDC_SLIDER_SECONDCOLOR_A        1024
#define IDC_SLIDER_CK_HUE               1024
#define IDC_SLIDER_RADIUS               1024
#define IDC_SLIDER_ANGLE1               1025
#define IDC_SLIDER_LOW_COLOR_G          1025
#define IDC_SLIDER_BORDER_COLOR_R       1025
#define IDC_SLIDER_FIRSTCOLOR_A         1025
#define IDC_SLIDER_CK_SAT_CROP          1025
#define IDC_SLIDER_ANGLE_PHI            1025
#define IDC_SLIDER_LENGTH1              1026
#define IDC_SLIDER_LOW_COLOR_B          1026
#define IDC_SLIDER_BORDER_COLOR_g       1026
#define IDC_SLIDER_CK_ANGLE             1026
#define IDC_SLIDER_ANGLE_THETA          1026
#define IDC_SLIDER_ANGLE2               1027
#define IDC_SLIDER_LOW_COLOR_A          1027
#define IDC_SLIDER_BORDER_COLOR_B       1027
#define IDC_SLIDER_DENSITY              1027
#define IDC_SLIDER_LIGHT_RATIO          1027
#define IDC_SLIDER_LENGTH2              1028
#define IDC_SLIDER_OFFSET               1028
#define IDC_SLIDER_BORDER_WIDTH         1028
#define IDC_CHECK_CK_INVERT             1028
#define IDC_SLIDER_FRONT_HIGH_LIGHT     1028
#define IDC_SLIDER_SOFTNESS             1029
#define IDC_SLIDER18                    1029
#define IDC_SLIDER_SOFT_WIDTH           1029
#define IDC_CHECK_YB_ON                 1029
#define IDC_SLIDER_FRONT_SMOOTHNESS     1029
#define IDC_SLIDER_BLURNESS             1030
#define IDC_SLIDER_FLIP2                1030
#define IDC_SLIDER_SLANT2               1030
#define IDC_SLIDER_YB_CLIP              1030
#define IDC_SLIDER_REAR_HIGH_LIGHT      1030
#define IDC_SLIDER_FINE_TUNE            1031
#define IDC_SLIDER_YB_GAIN              1031
#define IDC_SLIDER_REAR_SMOOTHNESS      1031
#define IDC_SLIDER_GRAY_MIN             1032
#define IDC_SLIDER_YB_LUM               1032
#define IDC_CHECK_USE_FORE_GROUND       1032
#define IDC_SLIDER_nSequence            1032
#define IDC_SLIDER_GRAY_MAX             1033
#define IDC_CHECK_CC_ON                 1033
#define IDC_SLIDER_MATTE_RATIO          1033
#define IDC_SLIDER_CC_LUM               1034
#define IDC_SLIDER_MATTE_R              1034
#define IDC_SLIDER_CC_SAT               1035
#define IDC_SLIDER_MATTE_G              1035
#define IDC_SLIDER_CC_HUE               1036
#define IDC_SLIDER_MATTE_B              1036
#define IDC_SLIDER_CC_CLIP              1037
#define IDC_SLIDER_TRANSITION           1037
#define IDC_SLIDER_CC_GAIN              1038
#define IDC_SLIDER_ANGLE_RT             1038
#define IDC_SLIDER_VW_SAT_CROP          1039
#define IDC_SLIDER_ANGLE_RB             1039
#define IDC_SLIDER_VW_ANGLE             1040
#define IDC_SLIDER_ANGLE_LB             1040
#define IDC_SLIDER_VW_MIX               1041
#define IDC_SLIDER_ANGLE_LB2            1041
#define IDC_SLIDER_VA_VGAIN             1042
#define IDC_SLIDER_ANGLE_LT             1042
#define IDC_SLIDER_VA_yGAIN             1043
#define IDC_SLIDER_STEP_PATTERN         1043
#define IDC_SLIDER_VA_CGAIN             1044
#define IDC_SLIDER_ANGLE_LB4            1044
#define IDC_SLIDER_GROUP_PATTERN        1044
#define IDC_SLIDER_fLocalTranslateX     1044
#define IDC_SLIDER22                    1045
#define IDC_SLIDER_VA_HUE               1045
#define IDC_SLIDER_fLocalTranslateY     1045
#define IDC_SLIDER_CKP_LEFT             1046
#define IDC_SLIDER_fLocalTranslateZ     1046
#define IDC_SLIDER_CKP_RIGHT            1047
#define IDC_SLIDER_fLocalRotateX        1047
#define IDC_SLIDER_CK_FILTER            1048
#define IDC_SLIDER_fLocalRotateY        1048
#define IDC_SLIDER_CC_FILTER            1049
#define IDC_SLIDER_fLocalRotateZ        1049
#define IDC_SLIDER_CCP_LEFT             1050
#define IDC_SLIDER_fScaleX              1050
#define IDC_SLIDER_CKP_RIGHT2           1051
#define IDC_SLIDER_CCP_RIGHT            1051
#define IDC_SLIDER_fScaleY              1051
#define IDC_SLIDER_fScaleZ              1052
#define IDC_SLIDER_fPositionX           1052
#define IDC_SLIDER_fWorldTranslateX     1053
#define IDC_SLIDER_fPositionY           1053
#define IDC_SLIDER_fWorldTranslateY     1054
#define IDC_SLIDER_fBorderWidth         1054
#define IDC_SLIDER_fWorldTranslateZ     1055
#define IDC_SLIDER_fShadowDropDistance  1055
#define IDC_SLIDER_fWorldRotateX        1056
#define IDC_SLIDER_fShadowDropLightAngle 1056
#define IDC_SLIDER_fWorldRotateY        1057
#define IDC_SLIDER_fShadowDropTransparency 1057
#define IDC_SLIDER_fWorldRotateZ        1058
#define IDC_SLIDER_fShadowDropSoftness  1058
#define IDC_SLIDER_fDirectionX          1059
#define IDC_SLIDER_dwTrailDecayType     1059
#define IDC_SLIDER_fDirectionY          1060
#define IDC_SLIDER_iTrailDecayTime      1060
#define IDC_SLIDER_fDiffuse             1061
#define IDC_SLIDER_dwBackGroundType     1061
#define IDC_CHECK_Light                 1062
#define IDC_SLIDER_fBackGoundDensity    1062
#define IDC_SLIDER_fAmbient             1063
#define IDC_STATIC_fSlant               1063
#define IDC_SLIDER_fBoundsLeft          1063
#define IDC_SLIDER_nDiveX               1064
#define IDC_STATIC_nSequence            1064
#define IDC_SLIDER_fBoundsTop           1064
#define IDC_SLIDER_nDiveY               1065
#define IDC_PRESIZE_X                   1065
#define IDC_SLIDER_fBoundsRight         1065
#define IDC_SLIDER_fIntervalX           1066
#define IDC_POST_SIZE_X                 1066
#define IDC_SLIDER_fBoundsBottom        1066
#define IDC_SLIDER_fIntervalY           1067
#define IDC_PRESIZE_Y                   1067
#define IDC_SLIDER_fTansparency         1067
#define IDC_SLIDER_crSlideColor_R       1068
#define IDC_SKEW_X                      1068
#define IDC_SLIDER_fKeyScaleX1          1068
#define IDC_SLIDER_fSlideTransparency   1069
#define IDC_POST_LOCATION_X             1069
#define IDC_SLIDER_fKeyScaleY1          1069
#define IDC_SLIDER_crSlideColor_B       1070
#define IDC_SKEW_Y                      1070
#define IDC_SLIDER_fKeyPositionX1       1070
#define IDC_SLIDER_BackgroundColor_B    1071
#define IDC_PERSPECTIVE                 1071
#define IDC_SLIDER_fKeyPositionY1       1071
#define IDC_SLIDER_crSlideColor_G       1072
#define IDC_POST_LOCATION_Y             1072
#define IDC_SLIDER_nKeyCount            1072
#define IDC_SLIDER_nRotate              1073
#define IDC_L_LOCATION_X                1073
#define IDC_SLIDER_fKeyScaleX2          1073
#define IDC_SLIDER_BackgroundColor_R    1074
#define IDC_POST_SIZE_Y                 1074
#define IDC_SLIDER_fKeyScaleY2          1074
#define IDC_SLIDER_BackgroundColor_G    1075
#define IDC__L_LOCATION_Z               1075
#define IDC_L_LOCATION_Z                1075
#define IDC_SLIDER_fKeyPositionX2       1075
#define IDC_SLIDER_fPerspective         1076
#define IDC_CHECK_BFLITER               1076
#define IDC_SLIDER_fKeyPositionY2       1076
#define IDC__L_LOCATION_Y               1077
#define IDC_L_LOCATION_Y                1077
#define IDC_CHECK_bFilter               1078
#define IDC_SLIDER_nDirecttion          1079
#define IDC_L_SPIN_X                    1079
#define IDC_EDIT_cBorderColor           1079
#define IDC_SLIDER_fTransition          1080
#define IDC_CHECK_bEnableShadow         1080
#define IDC_SLIDER_nType                1080
#define IDC_SLIDER_fBackgroundTransparency 1081
#define IDC_L_SPIN_Y                    1081
#define IDC_EDIT_cShadowColor           1081
#define IDC_SLIDER_fSlant               1081
#define IDC_CHECK_bReverse              1082
#define IDC_EDIT_cBackGroundSepiaColor  1082
#define IDC_SLIDER_fTrans               1082
#define IDC_L_ROTATION_X                1083
#define IDC_CHECK_bLinkCrop             1083
#define IDC_CHECK_bReverse1             1083
#define IDC_CHECK_FromOrTo              1083
#define IDC_CHECK_bEnabled              1083
#define IDC_SLIDER_movement             1084
#define IDC_L_SPIN_Z                    1085
#define IDC_SLIDER_movementRandom       1085
#define IDC_SLIDER_rotate               1086
#define IDC_L_ROTATION_Y                1087
#define IDC_SLIDER_centerX              1087
#define IDC_SLIDER_centerY              1088
#define IDC_L_ROTATION_Z                1089
#define IDC_SLIDER_aspect               1089
#define IDC_SLIDER_lightXDegree         1089
#define IDC_SLIDER_width                1090
#define IDC_SLIDER_lightYDegree         1090
#define IDC_L_SRC_SPIN_Y                1091
#define IDC_SLIDER_widthRandom          1091
#define IDC_SLIDER_diffuse2             1091
#define IDC_SLIDER_angleBlock           1092
#define IDC_SLIDER_ambient1             1092
#define IDC_L_SRC_SPIN_X                1093
#define IDC_SLIDER_randomPix            1093
#define IDC_SLIDER_ambient2             1093
#define IDC_SLIDER_fovDegree            1093
#define IDC_L_SRC_SPIN_Z                1095
#define IDC_SLIDER_mixType              1095
#define IDC_SLIDER_process              1096
#define IDC_L_AXIS_X                    1097
#define IDC_SLIDER_subtractr            1097
#define IDC_EDIT_FadeColor              1098
#define IDC_L_AXIS_Z                    1099
#define IDC_SLIDER_nPattern             1099
#define IDC_L_AXIS_Y                    1101
#define IDC_L_LOCATION_X2               1137
#define IDC__L_LOCATION_Z2              1138
#define IDC_L_LOCATION_Z2               1138
#define IDC__L_LOCATION_Y2              1139
#define IDC_L_LOCATION_Y2               1139
#define IDC_L_SPIN_X2                   1140
#define IDC_L_SPIN_Y2                   1141
#define IDC_L_ROTATION_X2               1142
#define IDC_L_SPIN_Z2                   1143
#define IDC_L_ROTATION_Y2               1144
#define IDC_L_ROTATION_Z2               1145
#define IDC_L_SRC_SPIN_Y2               1146
#define IDC_L_SRC_SPIN_X2               1147
#define IDC_L_SRC_SPIN_Z2               1148
#define IDC_L_AXIS_X2                   1149
#define IDC_L_AXIS_Z2                   1150
#define IDC_L_AXIS_Y2                   1151

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        333
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
